name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install project-specific dependencies from requirements.txt
        pip install -r backend/voice-cloning/requirements.txt
    - name: Create pylint config file
      run: |
        cat > .pylintrc << EOL
        [MASTER]
        fail-under=5.0
        
        [MESSAGES CONTROL]
        disable=
            import-error,
            missing-module-docstring,
            missing-function-docstring
        EOL
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
